### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by morontt** [morontt/zend-blog-3-backend#83]
- [x] tracking to archive rework
- [x] tracking on dashboard
- [x] update views count in articles
